### PR TITLE
Revert "♻️ bump packages versions"

### PR DESCRIPTION
**Pull request by Youssef1313**
Reverts unoplatform/uno.resizetizer#173

The update is causing issues: https://github.com/unoplatform/uno/pull/13878

### CODE REVIEW

**Comment by Youssef1313** [comment]
@mergify backport release/stable/1.1

**Comment by Youssef1313** [comment]
@pictos @jeromelaban Could you review and backport please?

**Comment by pictos** [comment]
@Youssef1313 lets await to see what's the issue caused on the Uno repo first

**Comment by Youssef1313** [comment]
@pictos I don't think the issue is Uno-specific. The SkiaSharp version used by Uno package is unrelated to the build failure happening. I'd guess the correct course of action is to add a binding redirect, but this is meant as a fast fix for the regression until the proper fix is done.

**Comment by pictos** [comment]
@Youssef1313 I bumped the skia version to the because of a vulnerability found on previous versions. Because of that I don't think downgrade is the correct fix. Let's await the resolution on the Uno PR and came with a plan

**Pull request closed without merging**
