### PR TITLE
fix: Create `IntermediateOutputPath` first if it doesn't exist

### PR DESCRIPTION
**Pull request by Youssef1313**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by dansiegel — APPROVED** [review]

**Review by jeromelaban — APPROVED** [review]

**Comment by pictos** [comment]
@Youssef1313 I could not reproduce the issue using my PC or Macbook, but this change doesn't break anything... It's redundancy since we create the folder on the tasks (on C# files). Can you confirm this change will fix your CI issues?

**Comment by Youssef1313** [comment]
@pictos I confirmed this fixed it, and actually I'm able to reproduce locally, not only in CI.

To reproduce, I'm doing `dotnet build` while `bin`/`obj` are deleted. The IDE have to be closed because it will re-create them.

**Comment by pictos** [comment]
@Youssef1313 did you reproduce it on Windows or Mac?

**Comment by Youssef1313** [comment]
On Windows.

**Comment by pictos** [comment]
I couldn't reproduce it locally either with our sample or using a project with the latest NuGet installed, following your steps. But this doesn't look to break anything, so I'll merge it.

Tks

**Pull request merged**
